name: Production

on:
    push: 
      paths:
        - 'web/**'
        - 'docker/web/**'
      branches: [ master ]
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v4
              
            - name: Install Node js
              uses: actions/setup-node@v4
              with:
                node-version: '18'

            - name: Install Packages and Build
              working-directory: web
              run: npm install --legacy-peer-deps && npm run build

    build:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Build Checkout
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}    

            - name: Build Image and Push
              run: |
                docker build -t portfolio-web -f docker/web/Dockerfile web 
                docker tag portfolio-web:latest monyorojoseph/portfolio-web:latest
                docker push monyorojoseph/portfolio-web:latest
    
    # deploy:
    #   runs-on: ubuntu-latest
    #   needs: build
    #   steps:
    #       - name: Deploy Web App
    #         uses: D3rHase/ssh-command-action@latest
    #         with:
    #           host: ${{ secrets.HOST }}
    #           port: ${{ secrets.PORT }}
    #           user: ${{ secrets.USER }}
    #           private_key: ${{ secrets.PRIVATE_KEY }}
    #           command: |
    #               "cd portfolio/ && docker compose pull && docker compose up --build -d"


